# Generated by Django 2.0.2 on 2018-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('iRank', models.IntegerField()),
                ('wRank', models.IntegerField()),
                ('description', models.TextField()),
                ('website', models.CharField(max_length=500)),
                ('acronym', models.CharField(max_length=50)),
                ('founded', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
    ]
